apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: /home/asah/old/docker2/kompose convert
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: kyrix
  name: kyrix
spec:
  ports:
  - name: "8000"
    port: 8000
    targetPort: 8000
  selector:
    io.kompose.service: kyrix
status:
  loadBalancer: {}
