#!/bin/bash

KV=${1:-asah/kyrix:1.6}

sudo docker build . -f Dockerfile-kyrix-kubernetes -t $KV
sudo docker push $KV

echo "updating kyrix-deployment.yaml"
sed -i "s@image:.*@image: $KV@" kyrix-deployment.yaml

echo "build done: to redeploy, run './redeploy-kyrix-server'"
