#!/bin/bash

TAG=${1:-asah/pg11_postgis25_citus811:1.3}

sudo docker build . -t $TAG
sudo docker push $TAG
sed -i "s@image: .*@image: $TAG@" worker-deployment.yaml
sed -i "s@image: .*@image: $TAG@" master-deployment.yaml

echo "docker build successful and {master,worker}-deployment.yaml updated"
