#!/bin/bash

# latest always gets pulled
TAG=${1:-asah/pg11_postgis25_citus811_plv8:latest}

sudo docker build . -f Dockerfile-citus-debian -t $TAG
sudo docker push $TAG
sed -i "s@image: .*@image: $TAG@" worker-deployment.yaml
sed -i "s@image: .*@image: $TAG@" master-deployment.yaml

echo "docker build successful and {master,worker}-deployment.yaml updated"
