#!/bin/bash

# latest always gets pulled
TAG=${1:-tracyhenry/pg11_postgis25_citus811_plv8:latest}

sudo docker build ../ -f ../docker-scripts/Dockerfile-db --target pg-plv8-citus -t $TAG
sudo docker push $TAG

#escaping / in $TAG
TAG=${TAG//\//\\\/};

# updating yaml files
perl -pi -e "s/image:.*/image: $TAG/g" k8s-yaml/worker-deployment.yaml
perl -pi -e "s/image:.*/image: $TAG/g" k8s-yaml/master-deployment.yaml

echo "docker build successful and {master,worker}-deployment.yaml updated"
