#!/bin/bash

KV=${1:-tracyhenry/kyrix:latest}

sudo docker build ../ -f ../docker-scripts/Dockerfile-kyrix-alpine -t $KV
sudo docker push $KV

#escaping / in $KV
KV=${KV//\//\\\/};

echo "updating k8s-yaml/kyrix-deployment.yaml"
perl -pi -e "s/image:.*/image: $KV/g" k8s-yaml/kyrix-deployment.yaml

echo "build done: to redeploy, run './redeploy-kyrix-server'"
