#!/bin/bash

# latest always gets pulled
TAG=${1:-asah/pg11_postgis25_citus811_plv8:latest}

sudo docker build ../ -f ../Dockerfile-citus-debian -t $TAG
sudo docker push $TAG

#escaping / in $TAG
TAG=${TAG//\//\\\/};

# updating yaml files
perl -pi -e "s/image:.*/image: $TAG/g" worker-deployment.yaml
perl -pi -e "s/image:.*/image: $TAG/g" master-deployment.yaml

echo "docker build successful and {master,worker}-deployment.yaml updated"
